# Generated by Django 5.2.1 on 2025-05-07 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_encuesta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
